<a href="https://colab.research.google.com/github/lorettarehm/AIML/blob/main/AAL_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load the data
data = pd.read_csv('AusApparalSales4thQrt2020.csv')

## 1. Data Wrangling

##### a. check for missing values

In [ ]:
data.isnull().sum()

Date     0
Time     0
State    0
Group    0
Unit     0
Sales    0
dtype: int64

There is no missing values in this data. If there were missing values , we could :

> * Drop rows with missing values : data.dropna()

> * Fill missing values : mean , median, mode data.fillna()

b. get summary statistics of data

In [ ]:
data.describe()

              Unit          Sales
count  7560.000000    7560.000000
mean     18.005423   45013.558201
std      12.901403   32253.506944
min       2.000000    5000.000000
25%       8.000000   20000.000000
50%      14.000000   35000.000000
75%      26.000000   65000.000000
max      65.000000  162500.000000

##### comment

#### b. Data Normalization ( Min-Max Scaling )

In [ ]:
data.head()

         Date        Time State     Group  Unit  Sales
0  1-Oct-2020     Morning    WA      Kids     8  20000
1  1-Oct-2020     Morning    WA       Men     8  20000
2  1-Oct-2020     Morning    WA     Women     4  10000
3  1-Oct-2020     Morning    WA   Seniors    15  37500
4  1-Oct-2020   Afternoon    WA      Kids     3   7500

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
data[['Unit', 'Sales']]= scaler.fit_transform(data[['Unit', 'Sales']])

In [ ]:
data

             Date        Time State     Group      Unit     Sales
0      1-Oct-2020     Morning    WA      Kids  0.095238  0.095238
1      1-Oct-2020     Morning    WA       Men  0.095238  0.095238
2      1-Oct-2020     Morning    WA     Women  0.031746  0.031746
3      1-Oct-2020     Morning    WA   Seniors  0.206349  0.206349
4      1-Oct-2020   Afternoon    WA      Kids  0.015873  0.015873
...           ...         ...   ...       ...       ...       ...
7555  30-Dec-2020   Afternoon   TAS   Seniors  0.190476  0.190476
7556  30-Dec-2020     Evening   TAS      Kids  0.206349  0.206349
7557  30-Dec-2020     Evening   TAS       Men  0.206349  0.206349
7558  30-Dec-2020     Evening   TAS     Women  0.142857  0.142857
7559  30-Dec-2020     Evening   TAS   Seniors  0.174603  0.174603

[7560 rows x 6 columns]

## 2. Data Analysis

Identifying higest and lowest revenue generating states

In [ ]:
data.groupby('State')['Sales'].sum().sort_values(ascending=False)

State
 VIC    635.968254
 NSW    441.714286
 SA     339.412698
 QLD    177.888889
 TAS    110.222222
 NT     109.079365
 WA     106.365079
Name: Sales, dtype: float64

In [ ]:
data.groupby('Group')['Sales'].sum().sort_values(ascending=False)

Group
 Men        484.444444
 Women      482.492063
 Kids       480.142857
 Seniors    473.571429
Name: Sales, dtype: float64

In [ ]:
data['Date'] = pd.to_datetime(data['Date'])

In [ ]:
data['Week']=data['Date'].dt.isocalendar().week

In [ ]:
data['Month']=data['Date'].dt.month

In [ ]:
weekly_sales =data.groupby('Week')['Sales'].sum().sort_values(ascending=False)

In [ ]:
monthly_sales =data.groupby('Month')['Sales'].sum().sort_values(ascending=False)

In [ ]:
data['Sales'].sum()

1920.6507936507937

In [ ]:
data

           Date        Time State     Group      Unit     Sales  Week  Month
0    2020-10-01     Morning    WA      Kids  0.095238  0.095238    40     10
1    2020-10-01     Morning    WA       Men  0.095238  0.095238    40     10
2    2020-10-01     Morning    WA     Women  0.031746  0.031746    40     10
3    2020-10-01     Morning    WA   Seniors  0.206349  0.206349    40     10
4    2020-10-01   Afternoon    WA      Kids  0.015873  0.015873    40     10
...         ...         ...   ...       ...       ...       ...   ...    ...
7555 2020-12-30   Afternoon   TAS   Seniors  0.190476  0.190476    53     12
7556 2020-12-30     Evening   TAS      Kids  0.206349  0.206349    53     12
7557 2020-12-30     Evening   TAS       Men  0.206349  0.206349    53     12
7558 2020-12-30     Evening   TAS     Women  0.142857  0.142857    53     12
7559 2020-12-30     Evening   TAS   Seniors  0.174603  0.174603    53     12

[7560 rows x 8 columns]

#### Data Visulaization

a.  State wise sales Analysis for Demgraphic data ( group , sales , state)

b. Group wise sales Analysis across State

c. Timewise , time of day analysis